#!/bin/bash

echo "Starting Phase 1"
python -W ignore Phase1.py
echo ""
echo "Starting Phase 2"
python -W ignore Phase2.py
echo ""
echo "Starting Phase 3"
python -W ignore Phase3.py
echo ""
echo "Starting Phase 4"
python -W ignore Phase4.py
echo ""
echo "Starting Phase 5"
python -W ignore Phase5.py
echo ""
echo "All done!"

