name: Publish
run-name: ${{ github.actor }} Publishing to PyPI
on:
    release:
        types:
            - released
            - prereleased
jobs:
    publish:
        name: Publish Release to PyPI
        runs-on: ubuntu-latest
        environment: release
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: pdm-project/setup-pdm@v4
            - name: Publish packages to PyPI
              run: pdm publish